name: 'Playwright Tests'
description: 'Run Playwright test and send report'
inputs:
  SHELL_TYPE:
    description: 'Shell type depend on OS where the code is running on'
    required: true
  OS_RUN:
    description: 'OS name run test'
    required: true
  BROWSER_RUN:
    description: 'Which browser run test'
    required: true
    default: 'chrome'
runs:
  # Composite is define group of steps, no runtime for each step
  using: 'composite'
  steps:
    - name: Run test with all specs option
      id: runWithAllSpecs
      shell: ${{ inputs.SHELL_TYPE }}
      run: |
        if ${{ inputs.BROWSER_RUN == 'all' }}; then    
          (ENV=example npx playwright test) || true
        else
          (ENV=example npx playwright test --project=${{ inputs.BROWSER_RUN }}) || true
        fi
