name: 'Playwright Tests'
description: 'Run Playwright test and send report'
inputs:
  SHELL_TYPE:
    description: 'Shell type depend on OS where the code is running on'
    required: true
  OS_RUN:
    description: 'OS name run test'
    required: true
  BROWSER_RUN:
    description: 'Which browser run test'
    required: true
    default: 'chrome'
  GITHUB_TOKEN:
    description: 'Github Token used to deploy GH pages'
    required: true

runs:
  # Composite is define group of steps, no runtime for each step
  using: 'composite'
  steps:
    - name: Get user context
      id: getUserContext
      shell: ${{ inputs.SHELL_TYPE }}
      run: |
        npm run generate-auth

    - name: Run test with all specs option
      id: runWithAllSpecs
      shell: ${{ inputs.SHELL_TYPE }}
      run: |
        if ${{ inputs.BROWSER_RUN == 'all' }}; then    
          (ENV=example npx playwright test) || true
        else
          (ENV=example npx playwright test --project=${{ inputs.BROWSER_RUN }}) || true
        fi

  # Allure Report Generation steps
    - name: Get Allure history
      uses: actions/checkout@v5
      if: ${{ steps.runWithAllSpecs.outcome == 'success' }}
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Generate Allure report
      uses: simple-elf/allure-report-action@master
      if: ${{ steps.runWithAllSpecs.outcome == 'success' }}
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ steps.runWithAllSpecs.outcome == 'success' }}
      with:
        # Auto create github_token when run workflow
        github_token: ${{ inputs.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v4
      if: ${{ steps.runWithAllSpecs.outcome == 'success' }}
      with:
        name: allure-report
        path: allure-report
        retention-days: 30

